import { IHousesEntity } from "../models/houses";
/*donnée fictif de house */

export const HOUSE: IHousesEntity[] = [
    {
        title: "Tipi",
        description: "Vivamus suscipit tortor eget felis porttitor volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot", "basket", "natation", "exploration montagne"],
        listidPics: ["/assets/img/house/tipi.jpg", "/assets/img/house/tente.jpg", "/assets/img/house/cabane.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"tipi",
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    },
    {
        title: "tente",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/tente.jpg", "/assets/img/house/tente.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"tente",        
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    },
    {
        title: "cabane dans les arbres",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/cabane.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"cabane",
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    },
    {
        title: "yourte",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/yourte.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"yourte",        
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    },
    {
        title: "cabane",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/cabane.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"cabane",        
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    },
    {
        title: "tente",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/tente.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        categories:"tente",        
        idUser: "2",
        listIdEquipements: ["tv", "radio"],
        listidTags: ["test"]
    }
];