import { IHousesEntity } from "../models/houses";
/*donnée fictif de house */

export const HOUSE: IHousesEntity[] = [
    {
        title: "Tipi",
        description: "jolie Tipi 00000000000000000000000000000 1111111111111111 ",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/tipi.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    },
    {
        title: "tente",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/tente.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    },
    {
        title: "cabane dans les arbres",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/cabane.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    },
    {
        title: "yourte",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/yourte.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    },
    {
        title: "cabane",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/cabane.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    },
    {
        title: "tente",
        description: "jolie typi",
        address: "44 rue de paris",
        zipecode: 75017,
        city: "paris",
        status: true,
        nbbeds: 2,
        price: 16,
        tax: 0,
        listeActivities: ["foot"],
        listidPics: ["/assets/img/house/tente.jpg"],
        dateDebut: "14:09:2021",
        dateFin: "14:09:2021",
        idCategory: "1",
        idUser: "2",
    }
];